/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_yeshen_test_hello_Jni */

#ifndef _Included_org_yeshen_test_hello_Jni
#define _Included_org_yeshen_test_hello_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_yeshen_test_hello_Jni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_yeshen_test_hello_Jni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     org_yeshen_test_hello_Jni
 * Method:    stringToJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_yeshen_test_hello_Jni_stringToJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
